use std::option::Option;
use serde::{Deserialize, Serialize};
use crate::job_store::{Job, JobResult, JobStatus};

/// Session search settings and other context formed by the frontend
/// immediately before a search request is submitted.
/// Request body accepted by `POST /api/v1/recipes/search`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveContext {
    /// Session-scoped search preferences (dietary mode, cuisine filter, etc.).
    /// Merged with persisted `global_preferences` by the orchestrator before
    /// the Gemini prompt is built.

    pub query: String,
    pub kitchen_appliances_id: u32
}


/// Immediate response to `POST /api/v1/recipes/search` — the job was accepted.
#[derive(Debug, Serialize)]
pub struct SearchRecipeResponse {
    pub job_id: String,
}

/// Token-usage metadata returned in the Gemini API `usageMetadata` field.
/// Used by `recipe_orchestrator.rs` to calculate the cost contribution of
/// a single Gemini call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelUsage {
    pub input_tokens: u32,
    pub output_tokens: u32,
}

/// The successful result of a completed recipe search job.
/// Returned inside the `result` key of `GET /api/v1/recipes/jobs/:job_id`
/// when the job status is `Completed`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecipeResponse {
    /// Finished recipe in Markdown format, generated by Gemini.
    pub markdown_content: String,

    /// Total cost in USD of all third-party API calls made for this job
    /// (SerpAPI searches + Gemini input/output tokens + Jina page fetches),
    /// rounded to six decimal places (e.g. `0.003842`).
    pub cost_usd: f64,
}

/// Full payload returned by `GET /api/v1/recipes/jobs/:job_id`.
#[derive(Debug, Serialize)]
pub struct JobStatusResponse {
    pub status: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<RecipeResponse>,

    /// Present only when `status == "failed"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Serialize)]
pub struct RecipeCostResult {
    pub markdown_content: String,
    pub cost_usd: f64,
}

#[derive(Serialize)]
pub struct RecipeJobResponse {
    pub job_id: String,
    pub status: &'static str,
    pub progress: u8,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<RecipeCostResult>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retry_after_minutes: Option<u32>,
}


impl RecipeJobResponse {
    pub fn from_job(job: &Job) -> Self {
        let status = job.status.as_str();

        Self {
            job_id: job.job_id.to_string(),
            status,
            progress: job.progress,
            result: match &job.status {
                JobStatus::Completed(JobResult::RecipeResult {
                                         markdown_content,
                                         cost_usd,
                                     }) => Some(RecipeCostResult {
                    markdown_content: markdown_content.clone(),
                    cost_usd: *cost_usd,
                }),
                _ => None,
            },
            error: match &job.status {
                JobStatus::Failed(reason) => Some(reason.clone()),
                JobStatus::RateLimited { message, .. } => Some(message.clone()),
                _ => None,
            },
            retry_after_minutes: match &job.status {
                JobStatus::RateLimited { retry_after_minutes, .. } => Some(*retry_after_minutes),
                _ => None,
            },
        }
    }
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EquipmentItem {
    pub name: String,
    pub description: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParsedRecipe {
    pub title: String,
    pub description: Option<String>,
    pub ingredients: Vec<String>,
    pub instructions: Vec<String>,
    pub cooking_time_minutes: Option<u32>,
    pub servings: Option<u32>,
    pub difficulty: Option<String>,
    pub equipment: Vec<EquipmentItem>,
    pub photo_url: Option<String>,
    pub source_url: String,
    pub source_title: String,
}




#[derive(serde::Deserialize)]
pub struct PageClassification {
    pub(crate) is_actual_recipe: bool,
    pub(crate) is_single_recipe: bool,
}