
CREATE TABLE IF NOT EXISTS countries (
                                         id   SERIAL PRIMARY KEY,
                                         code CHAR(2)  NOT NULL UNIQUE, -- ISO 3166-1 alpha-2, напр. "UA", "US"
                                         name TEXT     NOT NULL UNIQUE  -- напр. "Ukraine"
    );
INSERT INTO countries (code, name) VALUES
                                       ('AF', 'Afghanistan'),
                                       ('AL', 'Albania'),
                                       ('DZ', 'Algeria'),
                                       ('AO', 'Angola'),
                                       ('AR', 'Argentina'),
                                       ('AM', 'Armenia'),
                                       ('AU', 'Australia'),
                                       ('AT', 'Austria'),
                                       ('AZ', 'Azerbaijan'),
                                       ('BH', 'Bahrain'),
                                       ('BD', 'Bangladesh'),
                                       ('BY', 'Belarus'),
                                       ('BE', 'Belgium'),
                                       ('BZ', 'Belize'),
                                       ('BO', 'Bolivia'),
                                       ('BA', 'Bosnia and Herzegovina'),
                                       ('BW', 'Botswana'),
                                       ('BR', 'Brazil'),
                                       ('BN', 'Brunei'),
                                       ('BG', 'Bulgaria'),
                                       ('CM', 'Cameroon'),
                                       ('CA', 'Canada'),
                                       ('CL', 'Chile'),
                                       ('CN', 'China'),
                                       ('CO', 'Colombia'),
                                       ('CR', 'Costa Rica'),
                                       ('HR', 'Croatia'),
                                       ('CU', 'Cuba'),
                                       ('CZ', 'Czech Republic'),
                                       ('CD', 'Democratic Republic of the Congo'),
                                       ('DK', 'Denmark'),
                                       ('DO', 'Dominican Republic'),
                                       ('EC', 'Ecuador'),
                                       ('EG', 'Egypt'),
                                       ('SV', 'El Salvador'),
                                       ('EE', 'Estonia'),
                                       ('ET', 'Ethiopia'),
                                       ('FI', 'Finland'),
                                       ('FR', 'France'),
                                       ('GE', 'Georgia'),
                                       ('DE', 'Germany'),
                                       ('GH', 'Ghana'),
                                       ('GR', 'Greece'),
                                       ('GT', 'Guatemala'),
                                       ('HN', 'Honduras'),
                                       ('HK', 'Hong Kong'),
                                       ('HU', 'Hungary'),
                                       ('IS', 'Iceland'),
                                       ('IN', 'India'),
                                       ('ID', 'Indonesia'),
                                       ('IQ', 'Iraq'),
                                       ('IE', 'Ireland'),
                                       ('IL', 'Israel'),
                                       ('IT', 'Italy'),
                                       ('JM', 'Jamaica'),
                                       ('JP', 'Japan'),
                                       ('JO', 'Jordan'),
                                       ('KZ', 'Kazakhstan'),
                                       ('KE', 'Kenya'),
                                       ('KW', 'Kuwait'),
                                       ('LV', 'Latvia'),
                                       ('LB', 'Lebanon'),
                                       ('LY', 'Libya'),
                                       ('LT', 'Lithuania'),
                                       ('LU', 'Luxembourg'),
                                       ('MK', 'Macedonia'),
                                       ('MY', 'Malaysia'),
                                       ('MX', 'Mexico'),
                                       ('MD', 'Moldova'),
                                       ('MN', 'Mongolia'),
                                       ('MA', 'Morocco'),
                                       ('MZ', 'Mozambique'),
                                       ('NA', 'Namibia'),
                                       ('NP', 'Nepal'),
                                       ('NL', 'Netherlands'),
                                       ('NZ', 'New Zealand'),
                                       ('NI', 'Nicaragua'),
                                       ('NG', 'Nigeria'),
                                       ('NO', 'Norway'),
                                       ('OM', 'Oman'),
                                       ('PK', 'Pakistan'),
                                       ('PA', 'Panama'),
                                       ('PY', 'Paraguay'),
                                       ('PE', 'Peru'),
                                       ('PH', 'Philippines'),
                                       ('PL', 'Poland'),
                                       ('PT', 'Portugal'),
                                       ('PR', 'Puerto Rico'),
                                       ('QA', 'Qatar'),
                                       ('RO', 'Romania'),
                                       ('RU', 'Russia'),
                                       ('SA', 'Saudi Arabia'),
                                       ('SN', 'Senegal'),
                                       ('RS', 'Serbia'),
                                       ('SG', 'Singapore'),
                                       ('SK', 'Slovakia'),
                                       ('SI', 'Slovenia'),
                                       ('ZA', 'South Africa'),
                                       ('KR', 'South Korea'),
                                       ('ES', 'Spain'),
                                       ('LK', 'Sri Lanka'),
                                       ('SE', 'Sweden'),
                                       ('CH', 'Switzerland'),
                                       ('TW', 'Taiwan'),
                                       ('TZ', 'Tanzania'),
                                       ('TH', 'Thailand'),
                                       ('TN', 'Tunisia'),
                                       ('TR', 'Turkey'),
                                       ('UG', 'Uganda'),
                                       ('UA', 'Ukraine'),
                                       ('AE', 'United Arab Emirates'),
                                       ('GB', 'United Kingdom'),
                                       ('US', 'United States'),
                                       ('UY', 'Uruguay'),
                                       ('UZ', 'Uzbekistan'),
                                       ('VE', 'Venezuela'),
                                       ('VN', 'Vietnam'),
                                       ('YE', 'Yemen'),
                                       ('ZW', 'Zimbabwe')
    ON CONFLICT (code) DO NOTHING;
CREATE TABLE IF NOT EXISTS users (
                                     id         SERIAL PRIMARY KEY,
                                     name       TEXT NOT NULL UNIQUE,
                                     password   TEXT NOT NULL
    );
CREATE TABLE password_init_tokens (
                                      id          SERIAL PRIMARY KEY,
                                      user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                      token       VARCHAR(128) NOT NULL UNIQUE,  -- криптографічно стійкий випадковий токен
                                      expires_at  TIMESTAMPTZ NOT NULL,
                                      used_at     TIMESTAMPTZ NULL,              -- NULL = не використаний, NOT NULL = вже активований
                                      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS user_cookware (
                                             id          SERIAL PRIMARY KEY, -- Рекомендую додавати ID у кожну таблицю
                                             name        TEXT NOT NULL,
                                             description TEXT,
                                             user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS languages (
                                         id   SERIAL PRIMARY KEY,
                                         code CHAR(2) NOT NULL UNIQUE,
    name TEXT    NOT NULL UNIQUE
    );

INSERT INTO languages (code, name) VALUES
                                       ('af', 'Afrikaans'),
                                       ('ar', 'Arabic'),
                                       ('az', 'Azerbaijani'),
                                       ('be', 'Belarusian'),
                                       ('bg', 'Bulgarian'),
                                       ('bn', 'Bengali'),
                                       ('bs', 'Bosnian'),
                                       ('ca', 'Catalan'),
                                       ('cs', 'Czech'),
                                       ('da', 'Danish'),
                                       ('de', 'German'),
                                       ('el', 'Greek'),
                                       ('en', 'English'),
                                       ('es', 'Spanish'),
                                       ('et', 'Estonian'),
                                       ('fa', 'Persian'),
                                       ('fi', 'Finnish'),
                                       ('fr', 'French'),
                                       ('ga', 'Irish'),
                                       ('gl', 'Galician'),
                                       ('gu', 'Gujarati'),
                                       ('he', 'Hebrew'),
                                       ('hi', 'Hindi'),
                                       ('hr', 'Croatian'),
                                       ('hu', 'Hungarian'),
                                       ('hy', 'Armenian'),
                                       ('id', 'Indonesian'),
                                       ('is', 'Icelandic'),
                                       ('it', 'Italian'),
                                       ('ja', 'Japanese'),
                                       ('ka', 'Georgian'),
                                       ('kk', 'Kazakh'),
                                       ('km', 'Khmer'),
                                       ('ko', 'Korean'),
                                       ('lt', 'Lithuanian'),
                                       ('lv', 'Latvian'),
                                       ('mk', 'Macedonian'),
                                       ('mn', 'Mongolian'),
                                       ('ms', 'Malay'),
                                       ('mt', 'Maltese'),
                                       ('my', 'Burmese'),
                                       ('ne', 'Nepali'),
                                       ('nl', 'Dutch'),
                                       ('no', 'Norwegian'),
                                       ('pl', 'Polish'),
                                       ('pt', 'Portuguese'),
                                       ('ro', 'Romanian'),
                                       ('ru', 'Russian'),
                                       ('sk', 'Slovak'),
                                       ('sl', 'Slovenian'),
                                       ('sq', 'Albanian'),
                                       ('sr', 'Serbian'),
                                       ('sv', 'Swedish'),
                                       ('sw', 'Swahili'),
                                       ('ta', 'Tamil'),
                                       ('th', 'Thai'),
                                       ('tr', 'Turkish'),
                                       ('uk', 'Ukrainian'),
                                       ('ur', 'Urdu'),
                                       ('uz', 'Uzbek'),
                                       ('vi', 'Vietnamese'),
                                       ('zh', 'Chinese'),
                                       ('zu', 'Zulu')
    ON CONFLICT (code) DO NOTHING;
CREATE TABLE IF NOT EXISTS user_global_search_preference (
                                                             id         SERIAL PRIMARY KEY,
                                                             preference TEXT,
                                                             country_of_residence_id INTEGER REFERENCES countries(id) ON DELETE SET NULL,
    language_id             INTEGER REFERENCES languages(id) ON DELETE SET NULL,
    user_id    INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS user_ingredient (
                                               id              SERIAL PRIMARY KEY,
                                               name            TEXT NOT NULL,
                                               fill_percentage FLOAT NOT NULL, -- В Postgres краще FLOAT або NUMERIC
                                               photo_link      TEXT,
                                               user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS user_kitchen_appliances (
                                                       id          SERIAL PRIMARY KEY,
                                                       name        TEXT NOT NULL,
                                                       description TEXT,
                                                       user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS refresh_tokens (
                                              id         SERIAL PRIMARY KEY,
                                              jti        TEXT NOT NULL UNIQUE,
                                              user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_jti ON refresh_tokens(jti);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);